set number
set cursorline

"set highlt search"
set hls

set langmenu=UTF-8

set history=50

set tabstop=4
set smarttab
set shiftwidth=4
set softtabstop=4

set cmdheight=2
set showcmd
set ruler

set autoindent
set smartindent

syntax on
colorschem ron
filetype plugin indent on

"jump to the point where we quit last time."
set viminfo='10,\"100,:20,%,n~/.viminfo
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
