server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/kepserver        
        username: sayonara
        password: Iloveyouxuwu@121234

mybatis:
    configuration:
        map-underscore-to-camel-case: true
